importing

In [ ]:
import numpy as np

In [ ]:
# set precision
np.set_printoptions(precision=2)

creating matrix

In [ ]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim)

In [ ]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

- generate matrix   
    - linear
        - gap based
        - element based
    - random

In [ ]:
np.arange(1,100, 5)

In [ ]:
a = np.arange(-np.pi, np.pi, .25)
print(a)
a.size

In [ ]:
b = np.linspace(1, 10, 100)
print(b)

In [ ]:
b.reshape(25,4)

In [ ]:
b.reshape(5,5,4)

In [ ]:
print(np.random.rand(3,3))

In [ ]:
print(np.random.randn(5,5))

In [ ]:
print(np.random.randint(1, 100, (5,8)))

In [ ]:
x = np.random.randint(1, 11, (3,3))
y = np.random.randint(1, 11, (3,3))
print(x)
print(y)

In [ ]:
x + y # element wise addition

In [ ]:
x - 10

In [ ]:
x.dot(y)

In [ ]:
np.diag([1,2,2,4])

21 aug

In [ ]:
x = np.random.randint(20, 50, (6,6))
print(x)

In [ ]:
z = []
for i in x:
    for j in i:
        if j > 30:
            z.append(j)      
print(np.array(z))
# this is not the best way

In [ ]:
x > 30 # filter

In [ ]:
print(x[x>30]) # boolean filtering

In [23]:
f = x < 40
x[f]

array([23, 23, 37, 36, 37, 24, 23, 23, 28, 37, 20, 22, 35, 22, 32, 28, 34,
       30, 21, 27, 21, 30])

In [25]:
x[(x>30) & (x<45)]

array([44, 37, 36, 37, 44, 42, 37, 35, 41, 32, 34, 44, 44])

In [26]:
f1 = x > 30
f2 = x < 45
x[f1 & f2]

array([44, 37, 36, 37, 44, 42, 37, 35, 41, 32, 34, 44, 44])

slicing
1D = `[start : stop : step]`

2D = `[r_start: r_stop: r_step, c_start: c_stop: c_step]`

In [28]:
print('first row')
print(x[0])

first row
[47 23 45 46 46 23]


In [29]:
print('last row')
print(x[-1])

last row
[21 27 44 21 30 47]


In [30]:
print('slice 2 to 5')
print(x[2:6])

slice 2 to 5
[[23 48 47 23 28 44]
 [42 37 20 22 35 41]
 [22 32 28 34 44 30]
 [21 27 44 21 30 47]]


In [34]:
x[:, 0]

array([47, 46, 23, 42, 22, 21])

In [35]:
x[:, :3] # select first 3 columns

array([[47, 23, 45],
       [46, 44, 37],
       [23, 48, 47],
       [42, 37, 20],
       [22, 32, 28],
       [21, 27, 44]])

In [36]:
x[:, -3:] # select last 3 columns

array([[46, 46, 23],
       [36, 37, 24],
       [23, 28, 44],
       [22, 35, 41],
       [34, 44, 30],
       [21, 30, 47]])