importing

In [ ]:
import numpy as np

In [ ]:
# set precision
np.set_printoptions(precision=2)

creating matrix

In [ ]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim)

In [ ]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

- generate matrix   
    - linear
        - gap based
        - element based
    - random

In [ ]:
np.arange(1,100, 5)

In [ ]:
a = np.arange(-np.pi, np.pi, .25)
print(a)
a.size

In [ ]:
b = np.linspace(1, 10, 100)
print(b)

In [ ]:
b.reshape(25,4)

In [ ]:
b.reshape(5,5,4)

In [15]:
print(np.random.rand(3,3))

[[0.41 0.77 0.21]
 [0.59 0.48 0.71]
 [0.97 0.14 0.94]]


In [16]:
print(np.random.randn(5,5))

[[-0.21 -0.87  0.58 -0.81  0.09]
 [ 1.54 -0.69 -3.15  0.58  1.09]
 [-0.96 -1.37  0.88  1.46 -0.28]
 [ 0.31  0.48 -2.13 -1.12 -0.17]
 [-1.62 -1.    0.2   0.49  1.45]]


In [20]:
print(np.random.randint(1, 100, (5,8)))

[[94 36 27  8 26 68 26 24]
 [74 19 82 78 62 86 51 24]
 [12 73 90 47 46 33 69 39]
 [50 85 21 75 86 42 37 71]
 [27 29 71 20 68 70 74 70]]


In [22]:
x = np.random.randint(1, 11, (3,3))
y = np.random.randint(1, 11, (3,3))
print(x)
print(y)

[[8 5 3]
 [4 4 7]
 [4 7 9]]
[[5 6 3]
 [2 2 2]
 [1 9 8]]


In [24]:
x + y # element wise addition

array([[13, 11,  6],
       [ 6,  6,  9],
       [ 5, 16, 17]])

In [26]:
x - 10

array([[-2, -5, -7],
       [-6, -6, -3],
       [-6, -3, -1]])

In [27]:
x.dot(y)

array([[ 53,  85,  58],
       [ 35,  95,  76],
       [ 43, 119,  98]])